name: amarsolution_multikart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  http: ^1.1.0
  connectivity_plus: any
  url_launcher: ^6.2.2
  intl: any
  lottie: ^3.1.2
  logger: ^2.0.2+1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: any
  path_provider: any
  flutter_native_splash: any
  get: ^4.6.5
  get_storage: ^2.0.3
  barcode_scan2: ^4.3.1
  flutter_staggered_grid_view: ^0.7.0
  envied: ^0.5.4+1


# Flutter Splash Screen Setup
#
# This configuration helps you create a splash screen for your Flutter project.
#
# Instructions:
# 1. Add the following configuration to your pubspec.yaml file.
# 2. Run the command: flutter pub run flutter_native_splash:create
# 3. If you make any changes to the splash screen configuration, re-run the command.
#
# POS-Demo Configuration:
flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: assets/images/app_logo.png
  android_12:
    image: assets/images/app_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: any
  envied_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/